repos:
  - repo: local
    hooks:
      - id: open-mre
        name: format and lint open-mre
        language: system
        entry: make -C open_mre format lint
        files: ^open_mre/
        pass_filenames: false
