"""Prompt templates for LLM agents."""

from open_mre.prompts.templates import (
    BEHAVIOR_ANALYST_SYSTEM_PROMPT,
    CODE_EXTRACTOR_SYSTEM_PROMPT,
    EXECUTOR_SYSTEM_PROMPT,
    REPORT_GENERATOR_SYSTEM_PROMPT,
    VERSION_VALIDATOR_SYSTEM_PROMPT,
)

__all__ = [
    "BEHAVIOR_ANALYST_SYSTEM_PROMPT",
    "CODE_EXTRACTOR_SYSTEM_PROMPT",
    "EXECUTOR_SYSTEM_PROMPT",
    "REPORT_GENERATOR_SYSTEM_PROMPT",
    "VERSION_VALIDATOR_SYSTEM_PROMPT",
]
